#!/bin/bash

# docker source
source ../docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore.servicegateway/servicegatewayapi/bak
CONTAINER_NAME=$1_servicegateway_area1
mkdir $HOST_LOG_PATH/$CONTAINER_NAME

rm -rf $FOLDER_PATH/$1/etc
rm -rf $FOLDER_PATH/$1/authmodules
rm -rf $FOLDER_PATH/$1/External_SG
rm -rf $FOLDER_PATH/$1/Internal_SG

# setup config
cp -R $FOLDER_PATH/etc $FOLDER_PATH/$1/etc
cp -R $FOLDER_PATH/authmodules $FOLDER_PATH/$1/authmodules

sed -i "s/DB_DRIVER_URL/$DB_DRIVER_URL/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_AREA/$DB_AREA_2/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_USER/$DB_USER/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_PASSWORD/$DB_PASSWORD/" $FOLDER_PATH/$1/etc/proxool.xml

sed -i "s/SERVICE_AREA/$SERVICE_AREA_1/" $FOLDER_PATH/$1/etc/jadeconfig.plist.xml
sed -i "s/LOCALHOST/$LOCALHOST/" $FOLDER_PATH/$1/etc/jadeconfig.plist.xml
sed -i "s/SERVICE_AREA/$SERVICE_AREA_1/" $FOLDER_PATH/$1/etc/areaconfig.xml
sed -i "s/GATEWAY_PORT/$AREA2_GATEWAY_PORT/" $FOLDER_PATH/$1/etc/areaconfig.xml
sed -i "s/LOCALHOST/$LOCALHOST/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/PORTAL_SSL/$PORTAL_SSL/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/GATEWAY_PORT/$AREA2_GATEWAY_PORT/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/TRUST_IP_1_RANGE/$TRUST_IP_1_RANGE/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/TRUST_IP_3_RANGE/$TRUST_IP_3_RANGE/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/TRUST_IP_100_RANGE/$TRUST_IP_100_RANGE/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml
sed -i "s/TRUST_IP_150_RANGE/$TRUST_IP_150_RANGE/" $FOLDER_PATH/$1/etc/servicegatewayapiconfig.xml

# do unzip
unzip -d $FOLDER_PATH/$1 $FOLDER_PATH/$1/$1_servicegateway.zip

# run docker
docker run -d -v $FOLDER_PATH/$1/etc:/home/ecareme/etc/sg \
                -v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
                -v $FOLDER_PATH/$1/authmodules:/home/ecareme/authmodules \
                -v $FOLDER_PATH/$1/External_SG:/home/ecareme/src/sg/External_SG \
                -v $FOLDER_PATH/$1/Internal_SG:/home/ecareme/src/sg/Internal_SG \
                -v $FOLDER_PATH/script:/home/ecareme/script \
                -p $AREA1_GATEWAY_PORT:8080 \
                -p $AREA1_GATEWAY_SSL:8443 \
                --name $CONTAINER_NAME \
                $2 \
                /bin/bash -c ./home/ecareme/script/run

# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
