#!/bin/bash

# docker source
source ../docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore.filerelay/inforelayapi/bak
CONTAINER_NAME=$1_ir
mkdir $HOST_LOG_PATH/$CONTAINER_NAME

rm -rf $FOLDER_PATH/$1/etc
rm -rf $FOLDER_PATH/$1/ir

# setup config
cp -R $FOLDER_PATH/etc $FOLDER_PATH/$1/etc

sed -i "s/DB_DRIVER_URL/$DB_DRIVER_URL/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_AREA/$DB_AREA_2/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_USER/$DB_USER/" $FOLDER_PATH/$1/etc/proxool.xml
sed -i "s/DB_PASSWORD/$DB_PASSWORD/" $FOLDER_PATH/$1/etc/proxool.xml

sed -i "s/SERVICE_AREA/$SERVICE_AREA_2/" $FOLDER_PATH/$1/etc/areaconfig.xml

sed -i "s/TRUST_IP_1_RANGE/$TRUST_IP_1_RANGE/" $FOLDER_PATH/$1/etc/inforelayapiconfig.xml
sed -i "s/TRUST_IP_3_RANGE/$TRUST_IP_3_RANGE/" $FOLDER_PATH/$1/etc/inforelayapiconfig.xml
sed -i "s/TRUST_IP_100_RANGE/$TRUST_IP_100_RANGE/" $FOLDER_PATH/$1/etc/inforelayapiconfig.xml
sed -i "s/TRUST_IP_TW/$TRUST_IP_TW/" $FOLDER_PATH/$1/etc/inforelayapiconfig.xml
sed -i "s/LOCALHOST/$LOCALHOST/" $FOLDER_PATH/$1/etc/inforelayapiconfig.xml

# do unzip
unzip -d $FOLDER_PATH/$1/ir $FOLDER_PATH/$1/$1_inforelayapi.zip

# run docker
docker run -d -v $FOLDER_PATH/$1/etc:/home/ecareme/etc \
                -v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
                -v $FOLDER_PATH/$1/ir:/home/ecareme/src/ir \
                -v $FOLDER_PATH/script:/home/ecareme/script \
                -p $AREA2_IR_PORT:8080 \
                -p $AREA2_IR_SSL:8443 \
                --name $CONTAINER_NAME \
                $2 \
                /bin/bash -c ./home/ecareme/script/run

# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
