#!/bin/bash

# docker source
source docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore_cloud/coral/bak_facade
CONTAINER_NAME=$1_coral_facade
mkdir $HOST_LOG_PATH/$CONTAINER_NAME

rm -rf $FOLDER_PATH/$1/etc
rm -rf $FOLDER_PATH/$1/facade
rm -rf $FOLDER_PATH/$1/preproc
rm $FOLDER_PATH/$1/container_id

# setup config
cp -R $FOLDER_PATH/etc $FOLDER_PATH/$1/etc
cp -R $FOLDER_PATH/preproc $FOLDER_PATH/$1/preproc

sed -i "s/LOCALHOST/$LOCALHOST/" $FOLDER_PATH/$1/etc/coralfacade.plist.xml
sed -i "s/GATEWAY_PORT/$AREA2_GATEWAY_PORT/" $FOLDER_PATH/$1/etc/coralfacade.plist.xml
sed -i "s/CORAL_SERVER_PORT/$CORAL_SERVER_PORT/" $FOLDER_PATH/$1/etc/coralfacade.plist.xml

# do unzip
unzip -d $FOLDER_PATH/$1 $FOLDER_PATH/$1/$1_facade.zip

# run docker
docker run -d -v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
		-v $FOLDER_PATH/script:/home/ecareme/script \
		-p $CORAL_FACADE_PORT:8080 \
		--name $CONTAINER_NAME \
		$2 \
		/bin/bash -c ./home/ecareme/script/run >> $FOLDER_PATH/$1/container_id

# get container id
CONTAINER_ID=$(cat $FOLDER_PATH/$1/container_id)
echo $CONTAINER_ID

docker cp $FOLDER_PATH/$1/etc $CONTAINER_ID:/home/ecareme/etc/facade
docker cp $FOLDER_PATH/$1/facade $CONTAINER_ID:/home/ecareme/src
docker cp $FOLDER_PATH/$1/preproc $CONTAINER_ID:/home/ecareme/src

# start tomcat
docker exec $CONTAINER_ID ./home/ecareme/script/start_tomcat

# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
