#!/bin/bash

# docker source
source docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore_cloud/solrcommander/bak
CONTAINER_NAME=$1_solrcommander
mkdir $HOST_LOG_PATH/$CONTAINER_NAME

rm -rf $FOLDER_PATH/$1/etc
rm -rf $FOLDER_PATH/$1/solrcommander

# setup config
cp -R $FOLDER_PATH/etc $FOLDER_PATH/$1/etc
sed -i "s/LOCALHOST/$LOCALHOST/" $FOLDER_PATH/$1/etc/solrcommanderinfo.xml
sed -i "s/SOLRCOMMANDER_PORT/$SOLRCOMMANDER_PORT/" $FOLDER_PATH/$1/etc/solrcommanderinfo.xml

# do unzip
unzip -d $FOLDER_PATH/$1/solrcommander $FOLDER_PATH/$1/$1_solrcommander.zip

# run docker
docker run -d -v $FOLDER_PATH/$1/etc:/home/ecareme/etc/solrcommander \
		-v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
		-v $FOLDER_PATH/$1/solrcommander:/home/ecareme/src/solrcommander \
		-v $FOLDER_PATH/script:/home/ecareme/script \
		-p $SOLRCOMMANDER_PORT:8080 \
		--name $CONTAINER_NAME \
		$2 \
		/bin/bash -c ./home/ecareme/script/run 

# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
