#!/bin/bash

# docker source
source docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore_cloud/solr
CONTAINER_NAME=$1_solr

rm $FOLDER_PATH/$1/container_id

# run docker
docker run -d 	-v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
		-v $FOLDER_PATH/script:/home/ecareme/script \
		-p $SOLR_PORT:$SOLR_PORT \
		--name $CONTAINER_NAME \
		$2 \
		/bin/bash -c ./home/ecareme/script/run >> $FOLDER_PATH/$1/container_id

# get container id
CONTAINER_ID=$(cat $FOLDER_PATH/$1/container_id)
echo $CONTAINER_ID

docker cp $FOLDER_PATH/$1/solrcloud $CONTAINER_ID:/home/ecareme/src
docker cp $FOLDER_PATH/$1/etc $CONTAINER_ID:/home/ecareme/etc/solr

# start tomcat
docker exec $CONTAINER_ID ./home/ecareme/script/start_tomcat

# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
