#!/bin/bash

# docker source
source ../docker_env

# declare
FOLDER_PATH=$SOURCE_PATH/omnistore.filerelay/filerelayapi/bak
CONTAINER_NAME=$1_wr_area2
mkdir $HOST_LOG_PATH/$CONTAINER_NAME
ETC=$FOLDER_PATH/$1/etc_area2

rm -rf $ETC
rm -rf $FOLDER_PATH/$1/wr
rm $FOLDER_PATH/$1/container_id_area2

# setup config
cp -R $FOLDER_PATH/etc $ETC

sed -i "s/DB_DRIVER_URL/$DB_DRIVER_URL/" 	$ETC/proxool.xml
sed -i "s/DB_AREA/$DB_AREA_2/" 			$ETC/proxool.xml
sed -i "s/DB_USER/$DB_USER/" 			$ETC/proxool.xml
sed -i "s/DB_PASSWORD/$DB_PASSWORD/" 		$ETC/proxool.xml

sed -i "s/TRUST_IP_1_RANGE/$TRUST_IP_1_RANGE/" 		$ETC/webrelayapiconfig.xml
sed -i "s/TRUST_IP_3_RANGE/$TRUST_IP_3_RANGE/" 		$ETC/webrelayapiconfig.xml
sed -i "s/TRUST_IP_100_RANGE/$TRUST_IP_100_RANGE/" 	$ETC/webrelayapiconfig.xml
sed -i "s/TRUST_IP_150_RANGE/$TRUST_IP_150_RANGE/" 	$ETC/webrelayapiconfig.xml
sed -i "s/LOCALHOST/$LOCALHOST/" 			$ETC/webrelayapiconfig.xml
sed -i "s/GATEWAY_PORT/$AREA2_GATEWAY_PORT/" 		$ETC/webrelayapiconfig.xml
sed -i "s/METADATA_PORT/$AREA2_METADATA_PORT/" 		$ETC/webrelayapiconfig.xml
sed -i "s/PORTAL_SSL/$PORTAL_SSL/" 			$ETC/webrelayapiconfig.xml

# do unzip
unzip -d $FOLDER_PATH/$1/wr $FOLDER_PATH/$1/$1_filerelayapi.zip

# run docker
docker run -d -v $HOST_LOG_PATH/$CONTAINER_NAME:$LOG_ROOT \
		-v $FOLDER_PATH/script:/home/ecareme/script \
		-p $AREA2_WR_PORT:8080 \
		-p $AREA2_WR_SSL:8443 \
		--name $CONTAINER_NAME \
		$2 \
		/bin/bash -c ./home/ecareme/script/run >> $FOLDER_PATH/$1/container_id_area2

# get container id
CONTAINER_ID=$(cat $FOLDER_PATH/$1/container_id_area2)
echo $CONTAINER_ID

docker cp $ETC $CONTAINER_ID:/home/ecareme/etc/wr
docker cp $FOLDER_PATH/$1/wr $CONTAINER_ID:/home/ecareme/src/

# start tomcat
docker exec $CONTAINER_ID ./home/ecareme/script/start_tomcat


# syncState
#java -jar /home/ecareme/jar/syncState.jar 'new' $MODULE $FOLDER_MANE $(cat $FOLDER_MANE) $2

#rm $FOLDER_MANE
